# Configuration for self-consitency test on running ProteinMPNN and ESMFold.
defaults:
  - override hydra/launcher: joblib

inference:
  name: unconditional
  gpu_id: 0  # CUDA GPU to use
  seed: 33

  # Directory of backbones, ProteinMPNN, and outputs.
  backbone_pdb_dir: ./demo/unconditional/
  pmpnn_dir: ./tools/ProteinMPNN/
  output_dir: ./outputs/
  
  # Setting of ProteinMPNN
  CA_only: False

  samples:
    # Number of ESMFold samples per backbone sample.
    seq_per_sample: 10
    mpnn_batch_size: 1
    sort_by_score: True

  predict_method: [ESMFold]

  af2:
    executive_colabfold_path: path/to/your/executable_localcolabfold
    recycle: 10
    seed: 33
    model_type: alphafold2_ptm # {auto, alphafold2, alphafold2_multimer_{v1-v3}, deepfold_v1}
    num_models: 1 # {1,2,3,4,5}
    use_amber_relax: False
    num_relax: 3
    use_gpu_relax: False
    rank: ptm # {auto, plddt, ptm, iptm, multimer}